
(define-key attic-minor-mode-map (kbd "M-E")	 'mc/edit-lines)
(define-key attic-minor-mode-map (kbd "C-j C-r C-+") 'increment-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-N") 'rectangle-number-lines)
(define-key attic-minor-mode-map (kbd "C-j C-r C-b") 'bookmark-jump)
(define-key attic-minor-mode-map (kbd "C-j C-r C-c") 'clear-rectangle)
(define-key attic-minor-mode-map (kbd "C-j C-r C-d") 'delete-rectangle)
(define-key attic-minor-mode-map (kbd "C-j C-r C-f") 'frame-configuration-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-g") 'insert-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-i") 'insert-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-j") 'jump-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-k") 'kill-rectangle)
(define-key attic-minor-mode-map (kbd "C-j C-r C-l") 'bookmark-bmenu-list)
(define-key attic-minor-mode-map (kbd "C-j C-r C-m") 'bookmark-set)
(define-key attic-minor-mode-map (kbd "C-j C-r C-n") 'number-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-o") 'open-rectangle)
(define-key attic-minor-mode-map (kbd "C-j C-r C-r") 'copy-rectangle-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-s") 'copy-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-t") 'string-rectangle)
(define-key attic-minor-mode-map (kbd "C-j C-r C-w") 'window-configuration-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-x") 'copy-to-register)
(define-key attic-minor-mode-map (kbd "C-j C-r C-y") 'yank-rectangle)

(provide 'registry-bindings)
