;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-mode
        ace-jump-move
        align-regexp
        attic-lock-disable
        attic-rock-lock
        backward-delete-char
        backward-to-word
        comment-or-uncomment-region
        control-lock-enable
        delete-trailing-whitespace-and-save
        end-of-buffer
        erlang-electric-comma
        evil-backward-char
        evil-delete
        evil-delete-char
        evil-find-char
        evil-forward-char
        evil-forward-sentence
        evil-insert
        evil-normal-state
        evil-substitute
        forward-sentence
        ghc-insert-template
        ghc-save-buffer
        god-mode-disable
        god-mode-enable
        god-mode-self-insert
        haskell-indentation-delete-char
        haskell-newline-and-indent
        ido-switch-buffer
        inferior-haskell-load-file
        info
        iy-go-to-char
        iy-go-to-char--command
        kbd-macro-query
        keyboard-escape-quit
        kill-region
        load-haskell-workgroups
        magit-stage-item
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        orgtbl-self-insert-command
        pop-to-mark-command
        save-and-lock2
        select-window-1
        sgml-slash
        sh-assignment
        shm/:
        shrink-window-if-larger-than-buffer
        tab-to-tab-stop
        transpose-words
        undefined
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
