;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-mode
        ace-jump-move
        cua-copy-region
        cua-cut-region
        cua-delete-region
        cua-paste
        ghc-save-buffer
        haskell-indentation-delete-char
        inferior-haskell-load-file
        iy-go-to-char
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-self-insert-command
        select-window-1
        tab-to-tab-stop
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
