#! /bin/bash

ln -nfs "$(pwd)/vim/.vimrc"          "$HOME/.vimrc"
ln -nfs "$(pwd)/vim/.vim"            "$HOME/.vim"
sudo ln -nfs "$(pwd)/vim/.vimrc"     "/root/.vimrc"
sudo ln -nfs "$(pwd)/vim/.vim"       "/root/.vim"
ln -nfs "$(pwd)/zsh/.zshrc"          "$HOME/.zshrc"
ln -nfs "$(pwd)/zsh/.zsh"            "$HOME/.zsh"
