#! /bin/bash

ln -nfs "$(pwd)/emacs/.emacs"        "$HOME/.emacs"
ln -nfs "$(pwd)/emacs/.emacs.d"      "$HOME/.emacs.d"
sudo ln -nfs "$(pwd)/emacs/.emacs"   "/root/.emacs"
sudo ln -nfs "$(pwd)/emacs/.emacs.d" "/root/.emacs.d"
ln -nfs "$(pwd)/other/zsh/.zshrc"          "$HOME/.zshrc"
ln -nfs "$(pwd)/other/zsh/.zsh"            "$HOME/.zsh"
ln -nfs "$(pwd)/xmonad/xmonad.hs"    "$HOME/.xmonad/xmonad.hs"
ln -nfs "$(pwd)/urxvt/.Xdefaults"    "$HOME/.Xdefaults"
ln -nfs "$(pwd)/other/xmodmap/xmodmaprc"  "$HOME/.xmodmaprc"
ln -nfs "$(pwd)/other/xinit/.xinitrc"      "$HOME/.xinitrc"

ln -nfs "$(pwd)/other/elinks/elinks.conf"      "$HOME/.elinks/elinks.conf"
ln -nfs "$(pwd)/other/org"      "$HOME/org"

sudo cp "$(pwd)/urxvt/clipboard" "/usr/lib/urxvt/perl/clipboard"
