(tool-bar-mode 0)
(menu-bar-mode 0)
(scroll-bar-mode 0)
(global-linum-mode 1)
(cua-mode t)
(global-auto-complete-mode 1)
(multiple-cursors-mode 1)
(color-theme-midnight)
(put 'downcase-region 'disabled nil)
(modify-frame-parameters nil '((wait-for-wm . nil)))
(global-rainbow-delimiters-mode)
(workgroups-mode 1)
(wrap-region-mode 1)
(electric-pair-mode 1)
(setq org-log-done t)
(epa-file-enable)
(window-numbering-mode 1)
(ido-mode 1)
(yas-global-mode 1)
(smex-initialize)


(provide 'my-modes)
