* Todos

** Lazyvault
*** DONE Sandbox currently in use.
    CLOSED: [2013-01-18 Fri 13:57]
    List sandboxes needs to show which sandbox is in use at the moment.   

*** DONE Backup home .ghc / .cabal dirs.
    CLOSED: [2013-01-18 Fri 16:07]
    $HOME/.ghc and $HOME/.cabal need to be backed up if they exist.

*** DONE Remove sandbox
    CLOSED: [2013-01-18 Fri 16:48]
    The ability to remove an existing sandbox, and if
    the sandbox is selected at the time, the symlink must removed
    and the current selected sandbox must be removed.
*** TODO CmdArgs Package
    I need to implement CmdArgs for better UI usage.

*** TODO Cabalize
    Need to cabalize the project

*** TODO Create a default sandbox
    Create a sandbox where you store frequently used packages with the same version this 
    sandbox will be used to symlink certain packages to new sandboxes so it saves space.
*** TODO Sandbox create choose directory -- low priority
    I want to be able to choose my directory for my sandbox. So I can add all my packages inside of my Project.
    There should be a script to add a stray standbox to a lazyvault env variable.

    lv -c name -d /path/to/dir/
    
    add the path to .lazyDir/.customPaths


** EmacsHoogle
*** TODO Start Project
    Create a program to display hoogle results inside emacs instead of opening firefox.

** ScreenKey
*** TODO Start
   Examine the screenkey code and see if I can write something like that.
